# Generated by Django 4.0 on 2021-12-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Формат семплов')),
            ],
            options={
                'verbose_name': 'Формат',
                'verbose_name_plural': 'Форматы',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название стиля')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
            },
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=50, verbose_name='Автор')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('descriptions', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('size', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Размер в MB')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('link', models.TextField(verbose_name='Ссылка на сачивание файлов')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('format', models.ManyToManyField(to='xcd.Format', verbose_name='Формат')),
                ('style', models.ManyToManyField(to='xcd.Style', verbose_name='Стиль')),
            ],
            options={
                'verbose_name': 'Семплы',
                'verbose_name_plural': 'Семплы',
            },
        ),
    ]
