# Generated by Django 4.0 on 2021-12-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samples',
            name='format',
            field=models.ManyToManyField(related_name='format', to='xcd.Format', verbose_name='Формат'),
        ),
    ]
